lib: [
  "_build/install/default/lib/melange/META"
  "_build/install/default/lib/melange/dune-package"
  "_build/install/default/lib/melange/melange.a"
  "_build/install/default/lib/melange/melange.cma"
  "_build/install/default/lib/melange/melange.cmi"
  "_build/install/default/lib/melange/melange.cmt"
  "_build/install/default/lib/melange/melange.cmx"
  "_build/install/default/lib/melange/melange.cmxa"
  "_build/install/default/lib/melange/melange.ml"
  "_build/install/default/lib/melange/opam"
]
libexec: [
  "_build/install/default/lib/melange/melange.cmxs"
]
