(ns aoc-2025-07b
  (:require [clojure.string :as str]
            [clojure.java.io :as io]))


;; With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

;; With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

;; Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

;; To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

;; In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

;; .......S.......
;; .......|.......
;; ......|^.......
;; ......|........
;; .....|^.^......
;; .....|.........
;; ....|^.^.^.....
;; ....|..........
;; ...|^.^...^....
;; ...|...........
;; ..|^.^...^.^...
;; ..|............
;; .|^...^.....^..
;; .|.............
;; |^.^.^.^.^...^.
;; |..............
;; Or, there's the timeline where the particle alternated going left and right at each splitter:

;; .......S.......
;; .......|.......
;; ......|^.......
;; ......|........
;; ......^|^......
;; .......|.......
;; .....^|^.^.....
;; ......|........
;; ....^.^|..^....
;; .......|.......
;; ...^.^.|.^.^...
;; .......|.......
;; ..^...^|....^..
;; .......|.......
;; .^.^.^|^.^...^.
;; ......|........
;; Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

;; .......S.......
;; .......|.......
;; ......|^.......
;; ......|........
;; .....|^.^......
;; .....|.........
;; ....|^.^.^.....
;; ....|..........
;; ....^|^...^....
;; .....|.........
;; ...^.^|..^.^...
;; ......|........
;; ..^..|^.....^..
;; .....|.........
;; .^.^.^|^.^...^.
;; ......|........
;; In this example, in total, the particle ends up on 40 different timelines.

;; Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?


;; beam-map: sorted-map of {position -> timeline-count}
;; When a beam hits a splitter, it splits into left and right,
;; each inheriting the timeline count. Beams at the same position
;; have their counts summed.
(defn apply-beams [beam-map splitter-idxs]
  (let [splitter-set (set splitter-idxs)]
    (reduce (fn [acc [pos cnt]]
              (if (contains? splitter-set pos)
                (-> acc
                    (update (dec pos) (fnil + 0) cnt)
                    (update (inc pos) (fnil + 0) cnt))
                (update acc pos (fnil + 0) cnt)))
            (sorted-map)
            beam-map)))


;; (solve 7 [[7]])
;; Returns the total number of timelines after all layers.
(defn solve
  [start-pos splitter-layers]
  (->> (reduce apply-beams (sorted-map start-pos 1) splitter-layers)
       vals
       (reduce +)))


(defn parse-input [input]
  (->> input
       str/split-lines
       (map (fn [line]
               (keep-indexed #(when (= %2 \^) %1) line)))
       (filter seq)))


(->> "aoc_2025_07.input"
     io/resource
     slurp
     parse-input
     (solve 70)
     println)
